"""Direct TensorRT inference for SAM3 — bypasses transformers overhead entirely.

Two-engine architecture:
1. Vision encoder engine: pixel_values -> vision_embeds (~15-25ms)
2. Decoder engine: (vision_embeds, input_ids, attention_mask) -> raw outputs (~3-8ms)

Combined with batched decoder and fast preprocessing:
~20-33ms per frame = 30-50 FPS on RTX 3060 Laptop.

Uses torch CUDA tensors for buffer management (same pattern as fastsam_trt.py).
Pre-allocated I/O tensors, high-priority CUDA stream.

Requires:
- sam3_vision.engine (compiled from sam3_vision.onnx via trtexec --fp16)
- sam3_decoder.engine (compiled from sam3_decoder.onnx via trtexec --fp16)
- sam3_meta.json (generated by sam3_export.py)
"""

import json
import logging
import numpy as np
import cv2
import torch

logger = logging.getLogger(__name__)


class SAM3TRT:
    """Direct TensorRT SAM3 inference using torch CUDA tensors.

    Modeled after FastSAMTRT but adapted for the two-engine (vision + decoder)
    architecture of SAM3.
    """

    def __init__(self, vision_engine_path: str, decoder_engine_path: str,
                 meta_path: str = "sam3_meta.json"):
        import tensorrt as trt

        # Load metadata
        with open(meta_path) as f:
            self.meta = json.load(f)

        self._trt = trt

        # Preprocessing params
        self._img_h, self._img_w = self.meta["image_size"]
        self._img_mean = torch.tensor(self.meta["image_mean"], device="cuda", dtype=torch.float32).view(1, 3, 1, 1)
        self._img_std = torch.tensor(self.meta["image_std"], device="cuda", dtype=torch.float32).view(1, 3, 1, 1)
        self._do_rescale = self.meta.get("do_rescale", True)

        # High-priority CUDA stream (reduces DWM contention)
        self._stream = torch.cuda.Stream(priority=-1)

        # Pinned memory for fast CPU->GPU image upload
        self._upload_buf = torch.empty((self._img_h, self._img_w, 3),
                                       dtype=torch.uint8, device="cpu").pin_memory()
        self._upload_np = self._upload_buf.numpy()

        # --- Load vision encoder engine ---
        logger.info(f"Loading SAM3 TRT vision engine: {vision_engine_path}")
        self._vision_engine, self._vision_context = self._load_engine(
            vision_engine_path, trt
        )
        self._vision_inputs, self._vision_outputs = self._alloc_buffers(
            self._vision_engine, self._vision_context, trt
        )
        logger.info(f"  Vision engine loaded. Inputs: {list(self._vision_inputs.keys())}, "
                     f"Outputs: {list(self._vision_outputs.keys())}")

        # --- Load decoder engine ---
        logger.info(f"Loading SAM3 TRT decoder engine: {decoder_engine_path}")
        self._decoder_engine, self._decoder_context = self._load_engine(
            decoder_engine_path, trt
        )
        self._decoder_inputs, self._decoder_outputs = self._alloc_buffers(
            self._decoder_engine, self._decoder_context, trt
        )
        logger.info(f"  Decoder engine loaded. Inputs: {list(self._decoder_inputs.keys())}, "
                     f"Outputs: {list(self._decoder_outputs.keys())}")

        # Store output names for building result dicts
        self._decoder_output_names = self.meta.get("decoder_output_names", [])

        # Warmup both engines
        self._warmup()

    # ------------------------------------------------------------------
    # Engine loading and buffer allocation
    # ------------------------------------------------------------------

    def _load_engine(self, path: str, trt):
        """Load a TRT engine and create execution context."""
        trt_logger = trt.Logger(trt.Logger.WARNING)
        with open(path, "rb") as f:
            engine_data = f.read()

        runtime = trt.Runtime(trt_logger)
        engine = runtime.deserialize_cuda_engine(engine_data)
        if engine is None:
            raise RuntimeError(f"Failed to load TRT engine: {path}")

        context = engine.create_execution_context()
        return engine, context

    def _alloc_buffers(self, engine, context, trt):
        """Allocate torch CUDA tensors for all engine I/O and bind them."""
        inputs = {}
        outputs = {}

        for i in range(engine.num_io_tensors):
            name = engine.get_tensor_name(i)
            shape = list(engine.get_tensor_shape(name))
            dtype = engine.get_tensor_dtype(name)
            is_input = engine.get_tensor_mode(name) == trt.TensorIOMode.INPUT

            # Map TRT dtype to torch dtype
            if dtype == trt.float32:
                torch_dtype = torch.float32
            elif dtype == trt.float16:
                torch_dtype = torch.float16
            elif dtype == trt.int32:
                torch_dtype = torch.int32
            elif dtype == trt.int64:
                torch_dtype = torch.int64
            else:
                torch_dtype = torch.float32

            # Handle dynamic dimensions (-1) — use reasonable defaults
            alloc_shape = []
            for s in shape:
                if s < 0:
                    # Dynamic dim — allocate for max expected size
                    alloc_shape.append(16)  # reasonable max batch
                else:
                    alloc_shape.append(s)

            buf = torch.zeros(alloc_shape, dtype=torch_dtype, device="cuda")
            context.set_tensor_address(name, buf.data_ptr())

            if is_input:
                inputs[name] = buf
            else:
                outputs[name] = buf

            logger.info(f"    {'IN ' if is_input else 'OUT'} {name}: "
                        f"shape={shape} -> alloc={alloc_shape}, dtype={torch_dtype}")

        return inputs, outputs

    def _warmup(self):
        """Warmup both engines."""
        logger.info("  Warming up TRT engines...")

        # Vision warmup
        for _ in range(5):
            with torch.cuda.stream(self._stream):
                self._vision_context.execute_async_v3(self._stream.cuda_stream)
            self._stream.synchronize()

        # Decoder warmup
        for _ in range(5):
            with torch.cuda.stream(self._stream):
                self._decoder_context.execute_async_v3(self._stream.cuda_stream)
            self._stream.synchronize()

        torch.cuda.synchronize()
        logger.info("  TRT warmup complete")

    # ------------------------------------------------------------------
    # Preprocessing (fast path — bypass PIL and HF processor)
    # ------------------------------------------------------------------

    def preprocess(self, frame_bgr: np.ndarray) -> torch.Tensor:
        """Preprocess BGR frame to pixel_values tensor on GPU.

        Uses cv2 for resize, pinned memory for fast upload, GPU for normalize.
        ~2ms total vs ~15ms through PIL+HF processor.
        """
        # Resize on CPU (cv2 is fast)
        resized = cv2.resize(frame_bgr, (self._img_w, self._img_h),
                             interpolation=cv2.INTER_LINEAR)

        # BGR -> RGB
        rgb = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)

        # Write to pinned memory (zero-copy view)
        np.copyto(self._upload_np, rgb)

        # Upload to GPU and normalize
        with torch.cuda.stream(self._stream):
            gpu_u8 = self._upload_buf.cuda(non_blocking=True)  # (H, W, 3) uint8
            gpu_f32 = gpu_u8.float()

            if self._do_rescale:
                gpu_f32.div_(255.0)

            # HWC -> CHW, add batch dim
            pixel_values = gpu_f32.permute(2, 0, 1).unsqueeze(0)  # (1, 3, H, W)

            # Normalize
            pixel_values = (pixel_values - self._img_mean) / self._img_std

        return pixel_values

    # ------------------------------------------------------------------
    # Vision encoder inference
    # ------------------------------------------------------------------

    def encode_vision(self, pixel_values: torch.Tensor) -> torch.Tensor:
        """Run vision encoder TRT engine. Returns vision embeddings on GPU."""
        # Copy pixel_values into the pre-allocated input buffer
        pv_buf = self._vision_inputs.get("pixel_values")
        if pv_buf is not None:
            # Handle shape mismatch (dynamic batch)
            src_shape = pixel_values.shape
            if pv_buf.shape != src_shape:
                self._vision_context.set_input_shape("pixel_values", list(src_shape))

            pv_buf[:src_shape[0]] = pixel_values.to(pv_buf.dtype)
            self._vision_context.set_tensor_address("pixel_values", pv_buf.data_ptr())

        # Run inference
        with torch.cuda.stream(self._stream):
            self._vision_context.execute_async_v3(self._stream.cuda_stream)
        self._stream.synchronize()

        # Return the output (vision_embeds)
        # Try known name first, then first output
        if "vision_embeds" in self._vision_outputs:
            return self._vision_outputs["vision_embeds"].clone()
        elif "vision_embeds_0" in self._vision_outputs:
            return self._vision_outputs["vision_embeds_0"].clone()
        else:
            # Return first output
            first_key = next(iter(self._vision_outputs))
            return self._vision_outputs[first_key].clone()

    # ------------------------------------------------------------------
    # Decoder inference (batched)
    # ------------------------------------------------------------------

    def decode_batch(self, vision_embeds: torch.Tensor, input_ids: torch.Tensor,
                     attention_mask: torch.Tensor, batch_size: int) -> dict:
        """Run decoder TRT engine with batched inputs. Returns dict of output tensors."""
        trt = self._trt

        # Set dynamic input shapes for this batch
        vis_shape = list(vision_embeds.shape)
        vis_shape[0] = batch_size  # ensure batch dim
        ids_shape = list(input_ids.shape)
        ids_shape[0] = batch_size
        attn_shape = list(attention_mask.shape)
        attn_shape[0] = batch_size

        # Expand vision_embeds if needed
        if vision_embeds.shape[0] != batch_size:
            vision_embeds = vision_embeds.expand(batch_size, *vision_embeds.shape[1:])

        # Set input shapes for dynamic dimensions
        try:
            self._decoder_context.set_input_shape("vision_embeds", vis_shape)
            self._decoder_context.set_input_shape("input_ids", ids_shape)
            self._decoder_context.set_input_shape("attention_mask", attn_shape)
        except Exception as e:
            logger.warning(f"TRT set_input_shape failed: {e}")

        # Copy inputs into pre-allocated buffers
        vis_buf = self._decoder_inputs.get("vision_embeds")
        ids_buf = self._decoder_inputs.get("input_ids")
        attn_buf = self._decoder_inputs.get("attention_mask")

        if vis_buf is not None:
            # Reallocate if needed
            if vis_buf.shape[0] < batch_size or vis_buf.shape[1:] != vision_embeds.shape[1:]:
                vis_buf = torch.zeros_like(vision_embeds)
                self._decoder_inputs["vision_embeds"] = vis_buf
            vis_buf[:batch_size] = vision_embeds.to(vis_buf.dtype)
            self._decoder_context.set_tensor_address("vision_embeds", vis_buf.data_ptr())

        if ids_buf is not None:
            if ids_buf.shape[0] < batch_size:
                ids_buf = torch.zeros((batch_size, ids_buf.shape[1]),
                                      dtype=ids_buf.dtype, device="cuda")
                self._decoder_inputs["input_ids"] = ids_buf
            ids_buf[:batch_size, :input_ids.shape[1]] = input_ids.to(ids_buf.dtype)
            self._decoder_context.set_tensor_address("input_ids", ids_buf.data_ptr())

        if attn_buf is not None:
            if attn_buf.shape[0] < batch_size:
                attn_buf = torch.zeros((batch_size, attn_buf.shape[1]),
                                       dtype=attn_buf.dtype, device="cuda")
                self._decoder_inputs["attention_mask"] = attn_buf
            attn_buf[:batch_size, :attention_mask.shape[1]] = attention_mask.to(attn_buf.dtype)
            self._decoder_context.set_tensor_address("attention_mask", attn_buf.data_ptr())

        # Ensure output buffers are large enough and re-bind
        for name, buf in self._decoder_outputs.items():
            out_shape = self._decoder_context.get_tensor_shape(name)
            out_shape = [s if s > 0 else batch_size for s in out_shape]
            if any(s1 < s2 for s1, s2 in zip(buf.shape, out_shape)):
                new_buf = torch.zeros(out_shape, dtype=buf.dtype, device="cuda")
                self._decoder_outputs[name] = new_buf
                self._decoder_context.set_tensor_address(name, new_buf.data_ptr())

        # Run inference
        with torch.cuda.stream(self._stream):
            self._decoder_context.execute_async_v3(self._stream.cuda_stream)
        self._stream.synchronize()

        # Build output dict matching HF model output format
        result = {}
        for name, buf in self._decoder_outputs.items():
            result[name] = buf[:batch_size].clone()

        return result

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def shutdown(self):
        """Release TRT resources."""
        self._vision_engine = None
        self._vision_context = None
        self._decoder_engine = None
        self._decoder_context = None
        self._vision_inputs.clear()
        self._vision_outputs.clear()
        self._decoder_inputs.clear()
        self._decoder_outputs.clear()
        logger.info("SAM3TRT shutdown")
